server.port: 8888


skedulo.app:
  rate-limiter:
    resource:
      max-request: 120
      time-window-minute: 6
  config:
    limit-concurrent-coroutine: 10
    fetch-timeout-millis: 0

  retry-policy:
    condenser:
      maxAttempts: 3
      waitDurationSeconds: 2
