package com.share.services.graphql

sealed class EventModel(
    open val CustomFields: Map<String, Any?>?,
) {
    data class AvailabilitiesEventModel(
        val UID: String? = null,
        val ResourceId: String?,
        val Start: String?,
        val Finish: String?,
        val Status: String?,
        val IsAvailable: Boolean?,
        val Type: String?,
        val Notes: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class JobEventModel(
        val UID: String? = null,
        val AbortReason: String?,
        val AccountId: String?,
        val ActualEnd: String?,
        val ActualStart: String?,
        val Address: String?,
        val AutoSchedule: Boolean?,
        val CanBeDeclined: Boolean?,
        val CompletionNotes: String?,
        val ContactId: String?,
        val CopiedFromId: String?,
        val CustomerConfirmationStatus: String?,
        val Description: String?,
        val Duration: Int?,
        val End: String?,
        val EstimatedEnd: String?,
        val EstimatedStart: String?,
        val FollowupReason: String?,
        val GeoLatitude: Double?,
        val GeoLongitude: Double?,
        val IsGroupEvent: Boolean?,
        val JobAllocationTimeSource: Boolean?,
        val JobStatus: String?,
        val LocationId: String?,
        val Locked: Boolean?,
        val MaxAttendees: Int?,
        val MinAttendees: Int?,
        val Name: String?,
        val NotesComments: String?,
        val NotifyBy: String?,
        val NotifyPeriod: Int?,
        val ParentId: String?,
        val Quantity: Int?,
        val RecurringScheduleId: String?,
        val RegionId: String?,
        val ScheduleTemplateId: String?,
        val Start: String?,
        val TemplatedJobId: String?,
        val Type: String?,
        val Urgency: String?,
        val VirtualMeetingId: String?,
        val VirtualMeetingInfo: String?,
        val VirtualMeetingURL: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class JobAllocationsEventModel(
        val UID: String? = null,
        val DeclineDescription: String?,
        val DeclineReason: String?,
        val Duration: Int?,
        val End: String?,
        val EstimatedTravelDistance: Double?,
        val EstimatedTravelTime: Int?,
        val GeoCheckedInLatitude: Double?,
        val GeoCheckedInLongitude: Double?,
        val GeoCompletedLatitude: Double?,
        val GeoCompletedLongitude: Double?,
        val GeoInProgressLatitude: Double?,
        val GeoInProgressLongitude: Double?,
        val GeoStartTravelLatitude: Double?,
        val GeoStartTravelLongitude: Double?,
        val JobId: String?,
        val NotificationType: String?,
        val PhoneResponse: String?,
        val ResourceId: String?,
        val ResourceRequirementId: String?,
        val Start: String?,
        val Status: String?,
        val TeamLeader: Boolean?,
        val TimeCheckedIn: String?,
        val TimeCompleted: String?,
        val TimeInProgress: String?,
        val TimePublished: String?,
        val TimeResponded: String?,
        val TimeStartTravel: String?,
        val TravelDistance: Double?,
        val TravelTime: Int?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class AccountsEventModel(
        val UID: String? = null,
        val BillingCity: String?,
        val BillingPostalCode: String?,
        val BillingState: String?,
        val BillingStreet: String?,
        val Fax: String?,
        val Name: String?,
        val Phone: String?,
        val Rank: Int?,
        val RequiresWhitelist: Boolean?,
        val ShippingCity: String?,
        val ShippingPostalCode: String?,
        val ShippingState: String?,
        val ShippingStreet: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class ActivitiesEventModel(
        val UID: String? = null,
        val Address: String?,
        val CopiedFromId: String?,
        val End: String?,
        val GeoLatitude: Double?,
        val GeoLongitude: Double?,
        val LocationId: String?,
        val Notes: String?,
        val Quantity: Int?,
        val ResourceId: String?,
        val ScheduleTemplateId: String?,
        val Start: String?,
        val TemplatedActivityId: String?,
        val Timezone: String?,
        val Type: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class ContactsEventModel(
        val UID: String? = null,
        val AccountId: String?,
        val Email: String?,
        val FirstName: String?,
        val LastName: String?,
        val MailingCity: String?,
        val MailingPostalCode: String?,
        val MailingState: String?,
        val MailingStreet: String?,
        val MobilePhone: String?,
        val OtherCity: String?,
        val OtherPostalCode: String?,
        val OtherState: String?,
        val OtherStreet: String?,
        val Phone: String?,
        val RegionId: String?,
        val Title: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class JobTasksEventModel(
        val UID: String? = null,
        val Completed: Boolean?,
        val Description: String?,
        val JobId: String?,
        val Name: String?,
        val Seq: Int?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

    data class ResourcesEventModel(
        val UID: String? = null,
        val Alias: String?,
        val AutoSchedule: Boolean?,
        val Category: String?,
        val CountryCode: String?,
        val Email: String?,
        val EmploymentType: String?,
        val GeoLatitude: Double?,
        val GeoLongitude: Double?,
        val HomeAddress: String?,
        val IsActive: Boolean?,
        val MobilePhone: String?,
        val Name: String?,
        val Notes: String?,
        val NotificationType: String?,
        val PrimaryPhone: String?,
        val PrimaryRegionId: String?,
        val Rating: Int?,
        val ResourceType: String?,
        val UserId: String?,
        val WeeklyHours: Double?,
        val WorkingHourType: String?,
        override val CustomFields: Map<String, Any?>?,
    ) : EventModel(CustomFields)

}
